### ISSUE TITLE
Unable to use this chart with a smaller region

### ISSUE THREAD

**Issue by RubenNL** [RemiKalbe/overpass-api-helm-chart#2]
Hi,

I'm trying to use this chart with the `europe/netherlands` region, with this config;

```yaml
overpass:
  planetUrl: "https://download.geofabrik.de/europe/netherlands-latest.osm.pbf"
  diffUrl: "https://download.geofabrik.de/europe/netherlands-updates"
  updateFrequency: "daily"
  meta: "no"
```

The initial import seems to do the job just fine, but it failes when trying to use the updates.

This is the error:

```
https://download.geofabrik.de/europe/netherlands-updates/000/000/001.osc.gz:
2024-11-07 07:39:30 ERROR 404: Not Found.

gzip: stdin: unexpected end of file
```

I've attached the full log, but it seems like this 404 is the important part of this error.

[overpass-api.log](https://github.com/user-attachments/files/17657780/overpass-api.log)
