### ISSUE TITLE
DIFFS dir is missing

### ISSUE THREAD

**Issue by mstankala** [RemiKalbe/overpass-api-helm-chart#3]
Hi,

I've been waiting a long time for an example of how to run overpass-api using Helm charts on Kubernetes, and I appreciate that someone has finally started a project in this direction!

I noticed a missing configuration for the diffs directory in the https://github.com/RemiKalbe/overpass-api-helm-chart/blob/main/charts/overpass-api-chart/templates/statefulset.yaml  file, specifically in both the initContainer and main container sections. 
Here’s what I recommend adding to the volume mounts:

```yaml
volumeMounts:
  - name: data
    mountPath: /app/db
  - name: data
    mountPath: /app/work
  - name: scripts
    mountPath: /scripts
  - name: data
    mountPath: /app/diffs

```

This change should help ensure that the diffs directory is correctly mounted, when initializing the database.

Best regards,
Marek
